#!/usr/bin/env python3
"""Build deterministic, request-efficient website CSS and JavaScript bundles."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS_SOURCES = ("styles.css", "overrides.css", "pages.css", "dockly.css")
JS_SOURCES = ("script.js", "site.js")


def bundle(paths: tuple[str, ...], separator: str, banner: str) -> str:
    parts = [banner]
    for name in paths:
        content = (ROOT / name).read_text(encoding="utf-8").strip()
        parts.append(f"/* source: {name} */\n{content}")
    return separator.join(parts) + "\n"


def expected() -> dict[Path, str]:
    return {
        ROOT / "app.css": bundle(CSS_SOURCES, "\n", "/* Generated by scripts/build-site-assets.py. Do not edit directly. */"),
        ROOT / "app.js": bundle(JS_SOURCES, "\n;\n", "/* Generated by scripts/build-site-assets.py. Do not edit directly. */"),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed bundles are stale")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in expected().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"built {path.name} ({path.stat().st_size} bytes)")
    if stale:
        print("stale website bundles: " + ", ".join(stale), file=sys.stderr)
        print("run: make site-assets", file=sys.stderr)
        return 1
    if args.check:
        print("website bundles are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
