const state={apps:[],deployments:[],selected:null,setup:false};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});if(response.status===204)return null;const data=await response.json().catch(()=>({error:'Unexpected server response'}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function shortRepo(repo=''){return repo.replace(/^https?:\/\//,'').replace(/\.git$/,'')}
function age(value){if(!value)return '—';const seconds=Math.floor((Date.now()-new Date(value))/1000);if(seconds<60)return 'just now';if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`}
function icon(name){return (name||'?').slice(0,2).toUpperCase()}
function esc(value=''){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function statusLabel(status='idle'){return status.replace('-build','').replace(/^./,m=>m.toUpperCase())}
function appCard(app){return `<article class="app-card" data-app="${app.id}" tabindex="0" role="button" aria-label="Open ${esc(app.name)}"><div class="card-top"><span class="app-icon">${esc(icon(app.name))}</span><span class="status ${app.status}"><i></i>${esc(statusLabel(app.status))}</span></div><h3>${esc(app.name)}</h3><div class="repo-line">${esc(shortRepo(app.repository))}</div><div class="card-foot"><span>${esc(app.branch)}</span><span>:${app.publishPort} → :${app.port}</span></div></article>`}
function empty(title,copy){return `<div class="empty"><strong>${title}</strong>${copy}</div>`}
function activityRow(dep){const app=state.apps.find(a=>a.id===dep.appId);return `<div class="activity-row"><i class="rail-dot ${dep.status}"></i><strong>${esc(app?.name||'Removed application')}</strong><code>${esc(dep.commit?.slice(0,8)||'pending')}</code><span class="trigger">${esc(dep.trigger)}</span><span class="status ${dep.status}"><i></i>${esc(statusLabel(dep.status))}</span><time>${age(dep.startedAt)}</time></div>`}
function bindCards(){$$('[data-app]').forEach(el=>{const open=()=>openDetail(el.dataset.app);el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function render(){const healthy=state.apps.filter(a=>a.status==='running').length;$('#metric-apps').textContent=state.apps.length;$('#metric-healthy').textContent=healthy;$('#metric-deployments').textContent=state.deployments.length;const cards=state.apps.map(appCard).join('');$('#overview-apps').innerHTML=cards||empty('No applications yet','Connect a Git repository to make your first deployment.');$('#all-apps').innerHTML=cards||empty('Start with a repository','Dockly builds its Dockerfile and keeps each release ready to roll back.');const rows=state.deployments.map(activityRow).join('');$('#overview-activity').innerHTML=state.deployments.slice(0,5).map(activityRow).join('')||empty('No release activity','Deploy an application and its release trail will appear here.');$('#all-activity').innerHTML=rows||empty('No deployments yet','Build activity will appear here as soon as a deployment starts.');bindCards()}
async function load(){try{const [apps,deps,health]=await Promise.all([api('/api/apps'),api('/api/deployments'),api('/healthz')]);state.apps=apps.applications;state.deployments=deps.deployments;$('#engine-status').textContent=health.engineReady?'Connected':'Unavailable';$('#engine-chip').classList.toggle('unavailable',!health.engineReady);render();$('#auth').hidden=true;$('#dashboard').hidden=false}catch(error){if(error.message==='authentication required'){showAuth(false)}else toast(error.message)}}
function showAuth(setup){state.setup=setup;$('#dashboard').hidden=true;$('#auth').hidden=false;$('#auth-title').textContent=setup?'Set up your Dockly':'Welcome back';$('#auth-copy').textContent=setup?'Choose one strong password for this deployment console.':'Enter your console password to continue.';$('#auth-action').textContent=setup?'Set up Dockly':'Sign in';$('#password').autocomplete=setup?'new-password':'current-password'}
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const error=$('#auth-error');error.textContent='';try{const result=await api(state.setup?'/api/setup':'/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});if(result.webhookToken)window.prompt('Copy your Dockly webhook token. It is shown only during setup.',result.webhookToken);e.target.reset();await load()}catch(err){error.textContent=err.message}})
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});showAuth(false)};
$('#new-app').onclick=()=>$('#app-dialog').showModal();
$('#app-form').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return;const values=Object.fromEntries(new FormData(e.target));values.port=Number(values.port);values.publishPort=Number(values.publishPort);values.context='.';$('#app-error').textContent='';try{const data=await api('/api/apps',{method:'POST',body:JSON.stringify(values)});state.apps.push(data.application);e.target.reset();e.target.branch.value='main';e.target.dockerfile.value='Dockerfile';e.target.port.value='3000';e.target.publishPort.value='3000';e.target.healthPath.value='/';$('#app-dialog').close();render();toast('Application created')}catch(err){$('#app-error').textContent=err.message}})
$$('.nav-item[data-view]').forEach(button=>button.onclick=()=>switchView(button.dataset.view));$$('[data-jump]').forEach(button=>button.onclick=()=>switchView(button.dataset.jump));
function switchView(view){$$('.view').forEach(v=>v.hidden=v.id!==`${view}-view`);$$('.nav-item[data-view]').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$('#page-title').textContent=view==='apps'?'Applications':view==='activity'?'Activity':'Overview'}
$('#app-search').oninput=e=>{const query=e.target.value.toLowerCase();$('#all-apps').innerHTML=state.apps.filter(a=>`${a.name} ${a.repository}`.toLowerCase().includes(query)).map(appCard).join('')||empty('Nothing matched','Try a different application or repository name.');bindCards()};
async function openDetail(id){state.selected=id;const app=state.apps.find(a=>a.id===id);if(!app)return;$('#detail-name').textContent=app.name;$('#detail-repo').textContent=shortRepo(app.repository);$('#detail-dialog').showModal();showDetail('deployments')}
$('#detail-close').onclick=()=>$('#detail-dialog').close();$$('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));
async function showDetail(tab){$$('[data-detail]').forEach(b=>b.classList.toggle('active',b.dataset.detail===tab));const content=$('#detail-content');content.innerHTML='<div class="empty">Loading…</div>';try{if(tab==='deployments'){const data=await api(`/api/apps/${state.selected}/deployments`);content.innerHTML=data.deployments.map(activityRow).join('')||empty('No deployments','Deploy this application to create its first release.');content.querySelectorAll('.activity-row').forEach((row,i)=>{const dep=data.deployments[i];if(dep.status==='successful'){const b=document.createElement('button');b.className='text-button';b.textContent='Rollback';b.onclick=()=>rollback(dep.id);row.append(b)}})}else if(tab==='logs'){const data=await api(`/api/apps/${state.selected}/logs?lines=300`);content.innerHTML=`<pre>${esc(data.logs||'No container output.')}</pre>`}else{const app=state.apps.find(a=>a.id===state.selected);content.innerHTML=`<form class="env-editor"><p class="muted">One KEY=value per line. Values stay server-side and are never returned by the API.</p><textarea aria-label="Environment variables" placeholder="DATABASE_URL=…\nNODE_ENV=production"></textarea><button class="button primary" type="submit">Save environment</button></form>`;content.querySelector('form').onsubmit=saveEnv}}catch(err){content.innerHTML=empty('Could not load',esc(err.message))}}
async function saveEnv(e){e.preventDefault();const env={};for(const line of e.target.querySelector('textarea').value.split('\n')){if(!line.trim()||line.trim().startsWith('#'))continue;const at=line.indexOf('=');if(at<1)continue;env[line.slice(0,at).trim()]=line.slice(at+1)}try{await api(`/api/apps/${state.selected}/env`,{method:'PUT',body:JSON.stringify({env})});toast('Environment saved')}catch(err){toast(err.message)}}
$('#detail-deploy').onclick=async()=>{try{await api(`/api/apps/${state.selected}/deploy`,{method:'POST'});toast('Deployment queued');await load();openDetail(state.selected)}catch(err){toast(err.message)}};
$('#detail-refresh').onclick=()=>showDetail($('.detail-tabs button.active').dataset.detail);
async function rollback(id){if(!confirm('Roll back to this release?'))return;try{await api(`/api/apps/${state.selected}/rollback/${id}`,{method:'POST'});toast('Rollback queued');showDetail('deployments')}catch(err){toast(err.message)}}
(async()=>{try{const status=await api('/api/setup/status');if(status.required)showAuth(true);else await load()}catch{showAuth(false)}})();
setInterval(()=>{if(!$('#dashboard').hidden)load()},15000);
